name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch
  workflow_dispatch:      # Allow manual triggers

env:
  PROJECT_ID: erik-dev-896d1    # Google Cloud project ID
  REGION: us-west1           # Cloud Run region
  SERVICE_NAME: erik-dev    # Cloud Run service name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'  # Workload Identity Federation
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest

    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
        memory: 256Mi
        min_instances: 0
        max_instances: 10
        port: 8080
        timeout: 300
        allow-unauthenticated: true