name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: erik-dev-896d1    # Google Cloud project ID
  REGION: us-west1           # Cloud Run region
  SERVICE_NAME: erik-dev    # Cloud Run service name
  REPOSITORY: erik-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    # Configure docker for Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    # Try alternative authentication method
    - name: Docker Auth
      run: |
        # Authenticate with a more specific scope
        gcloud auth configure-docker us-west1-docker.pkg.dev --quiet
        
        # Get token directly
        echo "$(gcloud auth print-access-token)" | docker login -u oauth2accesstoken --password-stdin us-west1-docker.pkg.dev

    # Split build and push for better error visibility
    - name: Build Container
      run: |
        docker build -t us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

    # Add retries and verbose logging to push
    - name: Push Container
      run: |
        for i in 1 2 3; do
          echo "Push attempt $i..."
          docker push us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} && break
          sleep 10
        done

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        memory: 256Mi
        min_instances: 0
        max_instances: 10
        port: 8080
        timeout: 300
        allow-unauthenticated: true